GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "arto hellas",
    "number": "88-88-888888"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "arTO HEllas",
    "number": "88-88-888888"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "88-88-888888"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "arTO HEllas"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "James Bond",
    "number": "007"
}